import type { Metadata } from 'next';
import Link from 'next/link';

// Metadata for the About page
export const metadata: Metadata = {
  title: "About Ryan - My MS & AI Journey",
  description: "Learn about Ryan's personal journey with progressive Multiple Sclerosis and how he's leveraging AI, accessibility tools, and automation to regain capabilities and pursue creativity.",
};

export default function AboutPage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl prose lg:prose-lg xl:prose-xl dark:prose-invert">
      {/* Apply prose class to style the content generated by regular HTML */}
      <h1>Hello, I&apos;m Ryan.</h1> {/* Fixed: I'm -> I&apos;m */}
      <p>
        And this is where I share my journey of using AI, accessibility tools, and automation to adapt to the challenges of progressive Multiple Sclerosis. It&apos;s about finding creative new ways to reclaim capabilities and continue creating, even as my nerves are failing me.
      </p>

      <h2>The Unexpected Shift: From Programmer to Adaptor</h2>
      <p>
        For years, I built a career as a programmer, often taking for granted the seamless way my body interacted with technology. Hobbies like photography, which I poured myself into during COVID, or even just writing in an office, were a natural part of my life. The kid in me would have loved exploring bike trails, but even before my diagnosis, I felt a subtle, increasing loss of ability and interest in various activities, initially dismissing it as &quot;carpal tunnel&quot; requiring wrist braces. {/* Fixed: "carpal tunnel" -> &quot;carpal tunnel&quot; */}
      </p>
      <p>
        Then, nearly three years ago, after surviving COVID, my mother noticed my gait was in shambles. The subsequent MRI and spinal tap confirmed it: Progressive MS. These were outpatient procedures; I&apos;ve never been hospitalized, but the diagnosis was a stark, undeniable shift. My emotional state transitioned from denial to a gritty acceptance: <em>do what you can today, because you don&apos;t know what tomorrow will bring.</em> {/* Fixed: don't -> don&apos;t, doesn't -> doesn&apos;t */}
      </p>
      <p>
        Today, my cherished hobbies are largely out of reach. I can hardly walk around the block, and brain fog is a near-daily companion. Yet, I still have moments of lucidity, moments where clarity cuts through the haze. In those moments, I am driven to figure things out for myself and to document them for others. Because when things are inaccessible, I feel it deeply. Accessibility, for me, is no longer a feature to check; it&apos;s the fundamental handrails that allow movement.
      </p>

      <h2>AI: My New Launchpad for Lost Capabilities</h2>
      <p>
        My journey with AI intensified right around my diagnosis period, when I was deeply immersed in Midjourney v3. This was serendipitous, as tools like Launchpad, voice control, and keyboard shortcuts rapidly became not just conveniences, but necessities. I recognized early on that my limited energy and increasingly scarce moments of clarity demanded a smarter approach.
      </p>
      <p>
        As a former programmer with a growing interest in automation, I had a foundation of technical proficiency. This background proved invaluable as I navigated the world of AI. Where my physical capabilities diminished, automation and AI offered a substantial runway, a chance to hold onto the things I was once capable of.
      </p>
      <p>
        I refuse to be useless. As long as I can do something, I&apos;ll do it. Whether it&apos;s leveraging AI to generate painting ideas or manipulate visuals within the <strong>Adobe Suite, like Photoshop</strong>, when my hands can&apos;t perform precise mouse movements or intricate brushstrokes, I&apos;m constantly seeking innovative solutions. This is where my &quot;creative about going about being creative&quot; truly comes alive. {/* Fixed: I'll -> I&apos;ll, I'm -> I&apos;m, "creative..." -> &quot;creative...&quot; */}
      </p>

      <h2>Cutting Through the Noise, Building Trust</h2>
      <p>
        The internet can feel flooded with &quot;good enough, interesting enough slop,&quot; as I&apos;ve experienced. My answer to this isn&apos;t to compete on volume, but on value and authenticity. My work here is born from genuine necessity and lived experience. It&apos;s about providing valuable, trustworthy information that helps others&mdash;and helps me&mdash;navigate the complexities of MS with the aid of technology.
      </p>
      <p>
        I plan to become more active in MS communities, specifically on platforms like <Link href="https://www.reddit.com/r/MultipleSclerosis/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline dark:text-blue-400">Reddit</Link>, and engage in web accessibility discussions. <Link href="https://www.linkedin.com/in/YOUR_LINKEDIN_PROFILE/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline dark:text-blue-400">LinkedIn</Link> also feels like a natural fit, as the solutions I find for myself often have broader applications for anyone seeking greater efficiency or facing various accessibility challenges.
      </p>

      <h2>My Hope for You, and My Path Forward</h2>
      <p>
        After reading this page, I hope you feel a sense of hope and view me as a credible source for practical solutions and honest insights. The days of simply &quot;buckling down and doing it the hard way&quot; are long gone for me. My path now is about relentlessly pursuing the &quot;smart way,&quot; leveraging every tool available to maintain connection, creativity, and capability.
      </p>
      <p>
        The journey with MS is ongoing, but so is my commitment to finding and sharing new ways to live it fully.
      </p>
      <p>
        <Link href="/blog" className="text-blue-600 hover:underline dark:text-blue-400">Explore my blog for practical guides and insights &rarr;</Link>
      </p>
    </div>
  );
}